// Code generated by Kitex v0.12.1. DO NOT EDIT.

package pay

import (
	"context"
	pay "github.com/MakiJOJO/douyin-mall-echo/rpc_gen/kitex_gen/pay"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AliPay(ctx context.Context, Req *pay.PayRequest, callOptions ...callopt.Option) (r *pay.PayResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kPayClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPayClient struct {
	*kClient
}

func (p *kPayClient) AliPay(ctx context.Context, Req *pay.PayRequest, callOptions ...callopt.Option) (r *pay.PayResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AliPay(ctx, Req)
}
