// Code generated by Kitex v0.12.1. DO NOT EDIT.

package pay

import (
	"context"
	"errors"
	pay "github.com/MakiJOJO/douyin-mall-echo/rpc_gen/kitex_gen/pay"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"AliPay": kitex.NewMethodInfo(
		aliPayHandler,
		newAliPayArgs,
		newAliPayResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	payServiceInfo                = NewServiceInfo()
	payServiceInfoForClient       = NewServiceInfoForClient()
	payServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return payServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return payServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return payServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Pay"
	handlerType := (*pay.Pay)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "pay",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.12.1",
		Extra:           extra,
	}
	return svcInfo
}

func aliPayHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(pay.PayRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(pay.Pay).AliPay(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AliPayArgs:
		success, err := handler.(pay.Pay).AliPay(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AliPayResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAliPayArgs() interface{} {
	return &AliPayArgs{}
}

func newAliPayResult() interface{} {
	return &AliPayResult{}
}

type AliPayArgs struct {
	Req *pay.PayRequest
}

func (p *AliPayArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(pay.PayRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *AliPayArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *AliPayArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *AliPayArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AliPayArgs) Unmarshal(in []byte) error {
	msg := new(pay.PayRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AliPayArgs_Req_DEFAULT *pay.PayRequest

func (p *AliPayArgs) GetReq() *pay.PayRequest {
	if !p.IsSetReq() {
		return AliPayArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AliPayArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AliPayArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AliPayResult struct {
	Success *pay.PayResponse
}

var AliPayResult_Success_DEFAULT *pay.PayResponse

func (p *AliPayResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(pay.PayResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *AliPayResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *AliPayResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *AliPayResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AliPayResult) Unmarshal(in []byte) error {
	msg := new(pay.PayResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AliPayResult) GetSuccess() *pay.PayResponse {
	if !p.IsSetSuccess() {
		return AliPayResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AliPayResult) SetSuccess(x interface{}) {
	p.Success = x.(*pay.PayResponse)
}

func (p *AliPayResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AliPayResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) AliPay(ctx context.Context, Req *pay.PayRequest) (r *pay.PayResponse, err error) {
	var _args AliPayArgs
	_args.Req = Req
	var _result AliPayResult
	if err = p.c.Call(ctx, "AliPay", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
