global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s  #global catch time
    static_configs:
      - targets: ['127.0.0.1:9090']
  # prometheus port 9001
  - job_name: 'user'
    static_configs:
      - targets: [ 'localhost:9000' ]
        labels:
          job: user
          app: user
          env: dev
  - job_name: 'order'
    static_configs:
      - targets: [ 'localhost:9001' ]
        labels:
          job: order
          app: order
          env: dev
  - job_name: 'payment'
    static_configs:
      - targets: [ 'localhost:9002' ]
        labels:
          job: payment
          app: payment
          env: dev
  - job_name: 'cart'
    static_configs:
      - targets: [ 'localhost:9003' ]
        labels:
          job: cart
          app: cart
          env: dev
  - job_name: 'product'
    static_configs:
      - targets: [ 'localhost:9004' ]
        labels:
          job: product
          app: product
          env: dev
  - job_name: 'checkout'
    static_configs:
      - targets: [ 'localhost:9005' ]
        labels:
          job: checkout
          app: checkout
          env: dev
  - job_name: 'auth'
    static_configs:
      - targets: [ 'localhost:9006' ]
        labels:
          job: auth
          app: auth
          env: dev
  - job_name: 'ai_agent'
    static_configs:
      - targets: [ 'localhost:9007' ]
        labels:
          job: ai_agent
          app: ai_agent
          env: dev

  # - job_name: 'order-rpc'
  #   static_configs:
  #     - targets: [ 'douyin:4002' ]
  #       labels:
  #         job: order-rpc
  #         app: order-rpc
  #         env: dev
  # - job_name: 'order-mq'
  #   static_configs:
  #     - targets: [ 'douyin:4003' ]
  #       labels:
  #         job: order-mq
  #         app: order-mq
  #         env: dev

